"""
Ref: https://www.geeksforgeeks.org/print-subsequences-string/?ref=lbp

Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String,
that is generated by deleting some character of a given string without changing its order.

Input : abc
Output : a, b, c, ab, bc, ac, abc

Input : aaa
Output : a, aa, aaa
"""


def generate_all_subsequence(input_string, substring, curr_index):
    if curr_index == len(input_string):
        if substring != "":
            print("Subsequence: {}".format(substring))
        return
    generate_all_subsequence(input_string, substring + input_string[curr_index], curr_index + 1)
    generate_all_subsequence(input_string, substring, curr_index + 1)


def get_all_subsequence(input_string, substring, curr_index):
    if curr_index == len(input_string):
        if substring != "":
            print("Subsequence: {}".format(substring))
            return [substring]
        return []
    return get_all_subsequence(input_string, substring + input_string[curr_index],
                               curr_index + 1) + get_all_subsequence(input_string, substring, curr_index + 1)


if __name__ == "__main__":
    print("generating sub sequence of string..")
    generate_all_subsequence("abc", "", 0)
    print("populating result in array>>>>>>>>>>>>>>>>>")
    result = get_all_subsequence("abc", "", 0)
    print("Result: {}".format(result))
    print("populating result in array>>>>>>>>>>>>>>>>> \n\n\n")
    result = get_all_subsequence("abcd", "", 0)
    print("Result: {}".format(result))
